package Pb15;
/**
--- Jour 15 : Zone d'exclusion des balises ---
Vous sentez à nouveau le sol gronder alors que le signal de détresse vous mène à un vaste réseau de tunnels souterrains. Vous n'avez pas le temps de
tous les rechercher, mais vous n'en avez pas besoin : votre pack contient un ensemble de capteurs déployables que vous imaginez avoir été construits
à l'origine pour localiser les elfes perdus.

Les capteurs ne sont pas très puissants, mais ce n'est pas grave ; votre appareil portable indique que vous êtes suffisamment proche de la source du
signal de détresse pour les utiliser. Vous sortez le système de capteurs d'urgence de votre sac, appuyez sur le gros bouton en haut et les capteurs
s'éloignent dans les tunnels.

Une fois qu'un capteur a trouvé un endroit qui, selon lui, lui donnera une bonne lecture, il se fixe à une surface dure et commence à surveiller la
balise source de signal la plus proche. Les capteurs et les balises existent toujours à des coordonnées entières. Chaque capteur connaît sa propre
position et peut déterminer précisément la position d'une balise ; cependant, les capteurs ne peuvent se verrouiller que sur la balise la plus proche
du capteur , mesurée par la distance de Manhattan. Il n'y a jamais d'égalité lorsque deux balises sont à la même distance d'un capteur.

Il ne faut pas longtemps aux capteurs pour signaler leurs positions et les balises les plus proches (votre entrée de puzzle). Par exemple:

Sensor at x=2, y=18: closest beacon is at x=-2, y=15
Sensor at x=9, y=16: closest beacon is at x=10, y=16
Sensor at x=13, y=2: closest beacon is at x=15, y=3
Sensor at x=12, y=14: closest beacon is at x=10, y=16
Sensor at x=10, y=20: closest beacon is at x=10, y=16
Sensor at x=14, y=17: closest beacon is at x=10, y=16
Sensor at x=8, y=7: closest beacon is at x=2, y=10
Sensor at x=2, y=0: closest beacon is at x=2, y=10
Sensor at x=0, y=11: closest beacon is at x=2, y=10
Sensor at x=20, y=14: closest beacon is at x=25, y=17
Sensor at x=17, y=20: closest beacon is at x=21, y=22
Sensor at x=16, y=7: closest beacon is at x=15, y=3
Sensor at x=14, y=3: closest beacon is at x=15, y=3
Sensor at x=20, y=1: closest beacon is at x=15, y=3
Alors, considérons le capteur à 2,18 ; la balise la plus proche est à -2,15. Pour le capteur à 9,16, la balise la plus proche de lui est à 10,16.

En représentant les capteurs par S et les balises par B, la disposition ci-dessus des capteurs et des balises ressemble à ceci :

               1    1    2    2
     0    5    0    5    0    5
 0 ....S.......................
 1 ......................S.....
 2 ...............S............
 3 ................SB..........
 4 ............................
 5 ............................
 6 ............................
 7 ..........S.......S.........
 8 ............................
 9 ............................
10 ....B.......................
11 ..S.........................
12 ............................
13 ............................
14 ..............S.......S.....
15 B...........................
16 ...........SB...............
17 ................S..........B
18 ....S.......................
19 ............................
20 ............S......S........
21 ............................
22 .......................B....
Cependant, il ne s'agit pas nécessairement d'une carte complète de toutes les balises de la région. Étant donné que chaque capteur n'identifie que
sa balise la plus proche, si un capteur détecte une balise, vous savez qu'il n'y a pas d'autres balises proches ou plus proches de ce capteur. Il
pourrait encore y avoir des balises qui ne sont pas les balises les plus proches d'un capteur. Considérez le capteur à 8,7 :

               1    1    2    2
     0    5    0    5    0    5
-2 ..........#.................
-1 .........###................
 0 ....S...#####...............
 1 .......#######........S.....
 2 ......#########S............
 3 .....###########SB..........
 4 ....#############...........
 5 ...###############..........
 6 ..#################.........
 7 .#########S#######S#........
 8 ..#################.........
 9 ...###############..........
10 ....B############...........
11 ..S..###########............
12 ......#########.............
13 .......#######..............
14 ........#####.S.......S.....
15 B........###................
16 ..........#SB...............
17 ................S..........B
18 ....S.......................
19 ............................
20 ............S......S........
21 ............................
22 .......................B....
La balise la plus proche de ce capteur est à 2,10, et vous savez donc qu'il n'y a pas d'autre balise dans toutes les positions marquées #.

Aucune des balises détectées ne semble produire le signal de détresse, vous devrez donc déterminer où se trouve la balise de détresse en déterminant
où elle ne se trouve pas. Pour l'instant, pour simplifier compter les positions où une balise ne peut pas se trouver sur une seule ligne.

Donc, supposons que vous ayez un arrangement de balises et de capteurs comme dans l'exemple ci-dessus et, juste dans la ligne où y=10, vous voudriez
compter le nombre de positions où une balise ne peut pas exister. La couverture de tous les capteurs à proximité de cette rangée ressemble à ceci :

                 1    1    2    2
       0    5    0    5    0    5
 9 ...#########################...
10 ..####B######################..
11 .###S#############.###########.
Dans cet exemple, dans la rangée où y=10, il y a 26 positions où une balise ne peut pas être présente.

Consultez le rapport des capteurs que vous venez de déployer. Dans la rangée où y=2000000, combien de positions ne peuvent pas contenir de balise ?

Votre réponse au puzzle était 5073496.

--- Deuxième partie ---
Votre appareil portatif indique que le signal de détresse provient d'une balise à proximité. La balise de détresse n'est détectée par aucun capteur,
mais la balise de détresse doit avoir des coordonnées x et y non inférieure à 0 et non supérieure à 4000000.

Pour isoler le signal de la balise de détresse, vous devez déterminer sa fréquence d'accord , qui peut être trouvée en multipliant sa coordonnée x 
par 4000000 puis en ajoutant sa coordonnée y.

Dans l'exemple ci-dessus, l'espace de recherche est plus petit : à la place, les coordonnées x et y peuvent chacune être au plus égales à 20. Avec
cette zone de recherche réduite, il n'y a qu'une seule position qui pourrait avoir une balise : x = 14 et y = 11. La fréquence de syntonisation de
cette balise de détresse est 56000011.

Trouvez la seule position possible pour la balise de détresse. Quelle est sa fréquence d'accord ?

Votre réponse au puzzle était 13081194638237.
*/
